/*!40101 SET NAMES utf8mb4 */;

INSERT INTO `df_worldname` (`enname`, `krname`, `cnname`) VALUES
('USA', '미국', '美国'),
('Brazil', '브라질', '巴西'),
('India', '인도', '印度'),
('Russia', '러시아', '俄罗斯'),
('Peru', '페루', '秘鲁'),
('Chile', '칠레', '智利'),
('Mexico', '멕시코', '墨西哥'),
('South Africa', '남아프리카공화국', '南非'),
('Spain', '스페인', '西班牙'),
('UK', '영국', '英国'),
('Iran', '이란', '伊朗'),
('Pakistan', '파키스탄', '巴基斯坦'),
('Italy', '이탈리아', '意大利'),
('Saudi Arabia', '사우디아라비아', '沙特阿拉伯'),
('Turkey', '터키', '土耳其'),
('Germany', '독일', '德国'),
('Bangladesh', '방글라데시', '孟加拉国'),
('France', '프랑스', '法国'),
('Colombia', '콜롬비아', '哥伦比亚'),
('Argentina', '아르헨티나', '阿根廷'),
('Canada', '캐나다', '加拿大'),
('Qatar', '카타르', '卡塔尔'),
('Egypt', '이집트', '埃及'),
('Iraq', '이라크', '伊拉克'),
('China', '중국', '中国'),
('Indonesia', '인도네시아', '印度尼西亚'),
('Sweden', '스웨덴', '瑞典'),
('Ecuador', '에콰도르', '厄瓜多尔'),
('Belarus', '벨라루스', '白俄罗斯'),
('Kazakhstan', '카자흐스탄', '哈萨克斯坦'),
('Belgium', '벨기에', '比利时'),
('Oman', '오만', '阿曼'),
('Philippines', '필리핀', '菲律宾'),
('Kuwait', '쿠웨이트', '科威特'),
('Ukraine', '우크라이나', '乌克兰'),
('UAE', '아랍에미리트', '阿拉伯联合酋长国'),
('Bolivia', '볼리비아', '玻利维亚'),
('Netherlands', '네덜란드', '荷兰'),
('Panama', '파나마', '巴拿马'),
('Dominican Republic', '도미니카공화국', '多米尼加共和国'),
('Portugal', '포르투갈', '葡萄牙'),
('Singapore', '싱가포르', '新加坡'),
('Israel', '이스라엘', '以色列'),
('Poland', '폴란드', '波兰'),
('Afghanistan', '아프가니스탄', '阿富汗'),
('Bahrain', '바레인', '巴林'),
('Nigeria', '나이지리아', '尼日利亚'),
('Romania', '루마니아', '罗马尼亚'),
('Armenia', '아르메니아', '亚美尼亚'),
('Switzerland', '스위스', '瑞士'),
('Guatemala', '과테말라', '危地马拉'),
('Honduras', '온두라스', '洪都拉斯'),
('Ireland', '아일랜드', '爱尔兰'),
('Azerbaijan', '아제르바이잔', '阿塞拜疆'),
('Ghana', '가나', '加纳'),
('Japan', '일본.', '日本'),
('Algeria', '알제리', '阿尔及利亚'),
('Moldova', '몰도바', '摩尔多瓦'),
('Serbia', '세르비아', '塞尔维亚'),
('Austria', '오스트리아', '奥地利'),
('Nepal', '네팔', '尼泊尔'),
('Morocco', '모로코', '摩洛哥'),
('Cameroon', '카메룬', '喀麦隆'),
('Uzbekistan', '우즈베키스탄', '乌兹别克斯坦'),
('S. Korea', '한국', '韩国'),
('Czechia', '체코', '捷克'),
('Ivory Coast', '코트디부아르', '科特迪瓦'),
('Denmark', '덴마크', '丹麦'),
('Kyrgyzstan', '키르기스스탄', '吉尔吉斯斯坦'),
('Kenya', '케냐', '肯尼亚'),
('El Salvador', '엘살바도르', '萨尔瓦多'),
('Australia', '호주', '澳大利亚'),
('Sudan', '수단', '苏丹'),
('Venezuela', '베네수엘라', '委内瑞拉'),
('Norway', '노르웨이', '挪威'),
('Costa Rica', '코스타리카', '哥斯达黎加'),
('Malaysia', '말레이시아', '马来西亚'),
('North Macedonia', '북마케도니아', '北马其顿'),
('Senegal', '세네갈', '塞内加尔'),
('Ethiopia', '에티오피아', '埃塞俄比亚'),
('DRC', '콩고민주공화국', '刚果金'),
('Bulgaria', '불가리아', '保加利亚'),
('Bosnia and Herzegovina', '보스니아 헤르체고비나', '波黑'),
('Finland', '핀란드', '芬兰'),
('Palestine', '팔레스타인', '巴勒斯坦'),
('Haiti', '아이티', '海地'),
('Tajikistan', '타지키스탄', '塔吉克斯坦'),
('French Guiana', '프랑스령 기아나', '法属圭亚那'),
('Guinea', '기니', '几内亚'),
('Gabon', '가봉', '加蓬'),
('Madagascar', '마다가스카르', '马达加斯加'),
('Mauritania', '모리타니', '毛里塔尼亚'),
('Luxembourg', '룩셈부르크', '卢森堡'),
('Djibouti', '지부티', '吉布提'),
('CAR', '중앙아프리카공화국', '中非'),
('Hungary', '헝가리', '匈牙利'),
('Croatia', '크로아티아', '克罗地亚'),
('Greece', '그리스', '希腊'),
('Albania', '알바니아', '阿尔巴尼亚'),
('Thailand', '타이', '泰国'),
('Paraguay', '파라과이', '巴拉圭'),
('Nicaragua', '니카라과', '尼加拉瓜'),
('Somalia', '소말리아', '索马里'),
('Equatorial Guinea', '적도기니', '赤道几内亚'),
('Maldives', '몰디브', '马尔代夫'),
('Mayotte', '마요트섬', '马约特'),
('Sri Lanka', '스리랑카', '斯里兰卡'),
('Malawi', '말라위', '马拉维'),
('Lebanon', '레바논', '黎巴嫩'),
('Cuba', '쿠바', '古巴'),
('Mali', '말리', '马里'),
('Congo', '콩고', '刚果布'),
('South Sudan', '남수단', '南苏丹'),
('Estonia', '에스토니아', '爱沙尼亚'),
('Slovakia', '슬로바키아', '斯洛伐克'),
('Iceland', '아이슬란드', '冰岛'),
('Zambia', '잠비아', '赞比亚'),
('Lithuania', '리투아니아', '立陶宛'),
('Slovenia', '슬로베니아', '斯洛文尼亚'),
('Guinea-Bissau', '기니비사우', '几内亚比绍'),
('Cabo Verde', '카보베르데', '佛得角'),
('Sierra Leone', '시에라리온', '塞拉利昂'),
('Libya', '리비아', '利比亚'),
('Hong Kong', '홍콩', '香港'),
('New Zealand', '뉴질랜드', '新西兰'),
('Yemen', '예멘', '也门'),
('Eswatini', '에스와티니', '埃斯瓦蒂尼'),
('Rwanda', '르완다', '卢旺达'),
('Benin', '베냉', '贝宁'),
('Mozambique', '모잠비크', '莫桑比克'),
('Tunisia', '튀니지', '突尼斯'),
('Montenegro', '몬테네그로', '黑山'),
('Jordan', '요르단', '约旦'),
('Latvia', '라트비아', '拉脱维亚'),
('Niger', '니제르', '尼日尔'),
('Zimbabwe', '짐바브웨', '津巴布韦'),
('Liberia', '라이베리아', '利比里亚'),
('Uganda', '우간다', '乌干达'),
('Burkina Faso', '부르키나파소', '布基纳法索'),
('Cyprus', '키프로스', '塞浦路斯'),
('Uruguay', '우루과이', '乌拉圭'),
('Georgia', '조지아', '佐治亚州'),
('Namibia', '나미비아', '纳米比亚'),
('Chad', '차드', '乍得'),
('Andorra', '안도라', '安道尔'),
('Suriname', '수리남', '苏里南'),
('Jamaica', '자메이카', '牙买加'),
('Togo', '토고', '多哥'),
('Sao Tome and Principe', '상투메프린시페', '圣多美和普林西比'),
('San Marino', '산마리노', '圣马力诺'),
('Malta', '몰타', '马耳他'),
('Réunion', '레위니옹', '留尼汪'),
('Channel Islands', '채널제도', '海峡群岛'),
('Angola', '앙골라', '安哥拉'),
('Tanzania', '탄자니아', '坦桑尼亚'),
('Syria', '시리아', '叙利亚'),
('Taiwan', '대만', '台湾'),
('Botswana', '보츠와나', '博茨瓦纳'),
('Vietnam', '베트남', '越南'),
('Mauritius', '모리셔스', '毛里求斯'),
('Myanmar', '미얀마', '乌兰巴托'),
('Isle of Man', '맨섬', '马恩岛'),
('Comoros', '코모로', '科摩罗'),
('Guyana', '가이아나', '圭亚那'),
('Burundi', '부룬디', '布隆迪'),
('Mongolia', '몽골', '蒙古'),
('Lesotho', '레소토', '莱索托'),
('Martinique', '마르티니크섬', '马提尼克'),
('Eritrea', '에리트레아', '厄立特里亚'),
('Cayman Islands', '케이맨제도', '开曼群岛'),
('Guadeloupe', '과들루프섬', '瓜德罗普岛'),
('Faeroe Islands', '페로스제도', '法罗群岛'),
('Gibraltar', '지브롤터', '直布罗陀'),
('Cambodia', '캄보디아', '柬埔寨'),
('Bermuda', '버뮤다제도', '百慕大群岛'),
('Brunei ', '브루나이', '文莱'),
('Trinidad and Tobago', '트리니다드토바고', '特立尼达和多巴哥'),
('Bahamas', '바하마', '巴哈马'),
('Monaco', '모나코', '摩纳哥'),
('Aruba', '아루바', '阿鲁巴'),
('Barbados', '바베이도스', '巴巴多斯'),
('Seychelles', '세이셸', '塞舌尔'),
('Liechtenstein', '리히텐슈타인', '列支敦士登'),
('Bhutan', '부탄', '不丹'),
('Sint Maarten', '신트마르턴', '荷属圣马丁'),
('Antigua and Barbuda', '앤티가바부다', '安提瓜和巴布达'),
('Turks and Caicos', '터크스케이커스 제도', '特克斯和凯科斯群岛'),
('Gambia', '감비아', '冈比亚'),
('French Polynesia', '프랑스령폴리네시아', '法属波利尼西亚'),
('Macao', '마카오', '澳门'),
('Saint Martin', '세인트마틴섬', '圣马丁岛'),
('Belize', '벨리즈', '伯利兹'),
('St. Vincent Grenadines', '세인트빈센트그레나딘', '圣文森特和格林纳丁斯'),
('Curaçao', '퀴라소', '库拉索岛'),
('Fiji', '피지', '斐济'),
('Timor-Leste', '동티모르', '东帝汶'),
('Grenada', '그레나다', '格林纳达'),
('New Caledonia', '누벨칼레도니섬', '新喀里多尼亚'),
('Saint Lucia', '세인트루시아', '圣卢西亚'),
('Laos', '라오스', '老挝'),
('Dominica', '도미니카', '多米尼加'),
('Saint Kitts and Nevis', '세인트키츠네비스', '圣基茨和尼维斯'),
('Falkland Islands', '포클랜드제도', '福克兰群岛'),
('Greenland', '그린란드', '格陵兰岛'),
('Montserrat', '몬트세랫', '蒙特塞拉特'),
('Vatican City', '바티칸', '梵蒂冈城'),
('Papua New Guinea', '파푸아뉴기니', '巴布亚新几内亚'),
('Western Sahara', '서사하라', '西撒哈拉'),
('Caribbean Netherlands', '카리브 네덜란드', '荷兰加勒比区'),
('British Virgin Islands', '영국령 버진아일랜드', '英属维尔京群岛'),
('St. Barth', '생바르텔레미', '圣巴特'),
('Anguilla', '앵귈라', '安圭拉'),
('Saint Pierre Miquelon', '생피에르미클롱', '圣皮埃尔密克隆')

